@extends('app')
@section('content')
    <h1>Articles</h1>
    <hr/>
    <article>
        <h1>{{$article->title}}</h1>
        <article>
            {{$article->body}}
        </article>
    </article>
@stop